### ISSUE TITLE
Animation is not working on android just displaying svg

### ISSUE THREAD

**Issue by Dheeeraj** [kostimarko/rn-content-loader#2]
I did added d3-interpolate still no error or animation is coming up

**Comment by kostimarko** [comment]
Hey, Sorry for the delay.

Can you post the version and the code you're using? I tested mine out locally and it works

**Comment by Dheeeraj** [comment]
@kostimarko it was happening in the test mode. once i build the production app it works fine. i can work with it btw thanks for the library 🙂.

**Comment by kostimarko** [comment]
Can I close this?

**Comment by Dheeeraj** [comment]
Yes
