### ISSUE TITLE
viewBox not supported

### ISSUE THREAD

**Issue by nazarireza** [kostimarko/rn-content-loader#6]
Does any plan for add **viewBox** props to **AnimatedSvg** component?

**Comment by kostimarko** [comment]
Let me look into this. Submit a PR if you want.

**Comment by nazarireza** [comment]
> Let me look into this. Submit a PR if you want.

Sure, May I access the repository?

**Comment by nazarireza** [comment]
> Let me look into this. Submit a PR if you want.

https://github.com/kostimarko/rn-content-loader/pull/7#issue-261554395

**Comment by kostimarko** [comment]
merged:[2a98d3b]( https://github.com/kostimarko/rn-content-loader/commit/2a98d3bdc7c48a57a57775fb27d9b1947388ce73)
